export const data = [
  {
    portfolio: [
      {
        id: 0,
        img: "/img/portfolio/1.png",
        title: "My Weather App",
        des: "This app can quickly and easily check local weather and forecast weather conditions,you only need a mobile phone with Internet access.",
        date: "4 Dec 2023",
        used: "Next.js, Css ,javascript",
        role: "Frontend",
        view: "https://my-weather-app-gold-delta.vercel.app/",
      },
      {
        id: 1,
        img: "/img/portfolio/2.png",
        title: "Green Island Card-Collection",
        des: "Contains more than 140 types of hunter x hunter green island chapter cards.",
        date: "4 Dec 2023",
        used: "Next.js, Css ,javascript",
        role: "Frontend",
        view: "https://green-island-card-collection.vercel.app/",
      },
      {
        id: 2,
        img: "/img/portfolio/3.jpg",
        title: "i'm shiuan",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Minima esse perferendis corporis animi vero ipsa asperioresquae deleniti soluta sapiente aspernatur tempora, non nisidolorem! Iusto expedita, officiis rerum doloremque, nostrumdignissimos quidem quae sequi possimus voluptate eum doloremlibero.",
        date: "4 Dec 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "www.domain.com",
      },
      {
        id: 3,
        img: "/img/portfolio/4.jpg",
        title: "???",
        des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Minima esse perferendis corporis animi vero ipsa asperioresquae deleniti soluta sapiente aspernatur tempora, non nisidolorem! Iusto expedita, officiis rerum doloremque, nostrumdignissimos quidem quae sequi possimus voluptate eum doloremlibero.",
        date: "4 Dec 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "www.domain.com",
      },
      {
        id: 4,
        img: "/img/portfolio/5.jpg",
        title: "Restaurant app",
        des: "Responsive Single Page Website design for American restaurants",
        date: "8 Dec 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://foodwebsite-tawny.vercel.app/",
      },
      {
        id: 5,
        img: "/img/portfolio/6.jpg",
        title: "Game website design",
        des: "An introduction website designed with the theme of the DAEMON X MACHINA game.",
        date: "4 Jun 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://dxm-game-web.vercel.app/",
      },
    ],
  },
];

// des, date, used, Role, view, only use in popu
