export const data = [
  {
    portfolio: [
      {
        id: 3,
        img: "/img/portfolio/4.jpg",
        title: "GBF Game Web Design",
        des: "The website is mainly designed to design GBF game 3D carousel and Cyberpunk background.",
        date: "15 June 2024",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://gbf-slider3d.vercel.app/",
        git: "???",
      },
      {
        id: 0,
        img: "/img/portfolio/1.jpg",
        title: "My Weather App",
        des: "This app can quickly and easily check local weather and forecast weather conditions,you only need a mobile phone with Internet access.",
        date: "4 Dec 2023",
        used: "Next.js, Css ,javascript",
        role: "Frontend",
        view: "https://my-weather-app-gold-delta.vercel.app/",
        git: "???",
      },
      {
        id: 1,
        img: "/img/portfolio/2.jpg",
        title: "Green Island Card-Collection",
        des: "Contains more than 140 types of hunter x hunter green island chapter cards.",
        date: "4 Dec 2023",
        used: "Next.js, Css ,javascript",
        role: "Frontend",
        view: "https://green-island-card-collection.vercel.app/",
        git: "???",
      },
      {
        id: 10,
        img: "/img/portfolio/11.jpg",
        title: "Simple caculator App",
        des: "In addition to the basic four arithmetic operations, this computer application also provides advanced functions of square calculation, square root and percentage calculation .",
        date: "4 Jun 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://mycalculator-lake.vercel.app/",
        git: "???",
      },
      {
        id: 9,
        img: "/img/portfolio/7.jpg",
        title: "Draw Straws App",
        des: "A luck drawing program that can be used in games .",
        date: "4 Jun 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://rgb-clock-design.vercel.app/",
        git: "???",
      },
      {
        id: 8,
        img: "/img/portfolio/10.jpg",
        title: "RGB Digital Clock",
        des: "An app that includes pocket watch design and digital clock .",
        date: "4 Jun 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://rgb-clock-design.vercel.app/",
        git: "???",
      },
      {
        id: 7,
        img: "/img/portfolio/9.jpg",
        title: "3D-GameCard design",
        des: "An app that uses css rotate and js functions Math.atan2() to present 3D and reflective effects .",
        date: "4 Jun 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://yugioh-3d-card.vercel.app/",
        git: "???",
      },
      {
        id: 6,
        img: "/img/portfolio/8.jpg",
        title: "Todo List App",
        des: "Use LocalStorage to create a simple todo app, including the functions of editing lists and completing list browsing .",
        date: "4 Jun 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://my-to-dolist.vercel.app/",
        git: "???",
      },
      {
        id: 2,
        img: "/img/portfolio/3.jpg",
        title: "i'm shiuan",
        des: "This is a website about me.",
        date: "4 Dec 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://shiuan-portfolio.vercel.app/profolio",
        git: "???",
      },
      {
        id: 4,
        img: "/img/portfolio/5.jpg",
        title: "Restaurant app",
        des: "Responsive Single Page Website design for American restaurants",
        date: "8 Dec 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://foodwebsite-tawny.vercel.app/",
        git: "???",
      },
      {
        id: 5,
        img: "/img/portfolio/6.jpg",
        title: "Game website design",
        des: "An introduction website designed with the theme of the DAEMON X MACHINA game.",
        date: "4 Jun 2020",
        used: "Html, Css ,javascript",
        role: "Frontend",
        view: "https://dxm-game-web.vercel.app/",
        git: "???",
      },
    ],
  },
];

// des, date, used, Role, view, only use in popu
